export const quips = [
  "Ba dum tsss",
  "...I'll see myself out.",
  "*crickets*",
  "Thank you, I'm here all week.",
  "No refunds.",
  "Try the veal.",
  "*nervous laughter*",
  "...anyway, back to coding.",
  "10/10, would compile again.",
  'git commit -m "added humor"',
  "Segfault in humor module.",
  "rm -rf doubts",
  "Error 418: I'm a teapot.",
  "Works on my machine.",
  "Have you tried turning it off and on again?",
  "This joke is O(n) funny.",
  "Pushed to main. No regrets.",
  "// TODO: write better joke",
  "Joke shipped. Zero test coverage.",
  "That's what she sed.",
  "sudo make me laugh",
  "404: Punchline not found.",
  "Merge conflict in humor.ts",
  "Deploying laughter to production...",
  "LGTM.",
  "pip install laughter",
  "Rebasing my sense of humor.",
  "This is fine. Everything is fine.",
  "Ctrl+Z that from your memory.",
  "chmod 777 jokes/",
  "Joke reviewed. 2 approvals.",
  "Hotfix incoming.",
  "That joke has been deprecated.",
  "Rolling back to a funnier version.",
  "Compiling punchline... done.",
  "null pointer to humor detected.",
  "Joke passed CI. Somehow.",
  "docker run --rm humor:latest",
  "Latency on that punchline was rough.",
  "Caching that joke for later.",
  "This joke runs in O(lol) time.",
  "Refactoring my comedic timing.",
  "Breaking change: humor v2.0",
  "Feature flag: --enable-comedy",
  "PR merged: add-joke-support",
  "Rollback complete. Humor restored.",
  "kubectl apply -f joke.yaml",
  "Monitoring joke uptime... 99.9%",
  "That one's going in the sprint retro.",
  "console.log('haha')",
];
